#!/usr/bin/env python3
"""One draft PR per UPS Center week -- created, updated, or (if an editor owns it) only
commented on. Never merged, never marked ready, never published, never announced.

Keith 2026-10-08: "Make the process idempotent: later Elias corrections update that
week's existing draft and identify changed claims; they must not create a second
issue ... it should never publish or post on its own."

Decision for week W (article <season>-wkNN-ups-center), from the open PRs that touch
that article's file:
  none                                   -> CREATE a draft PR from branch wire/auto/<id>
  the automation's own PR, same claims   -> NOOP
  the automation's own PR, claims moved  -> UPDATE: rebuild the branch from origin/main,
                                            force-push it (the branch is automation-owned),
                                            rewrite the PR body, comment the changed claims
  any PR an editor owns (another branch,
  or a commit on the auto branch without
  the automation's trailer)              -> COMMENT the re-check (changed claims, quote
                                            problems) once per distinct result; never
                                            touch the editor's branch
  more than one PR for the article        -> STOP and alert (a duplicate already exists)

Every git/gh call goes through `run`, so tests drive this with a fake.
"""
import hashlib
import json
import re

TRAILER = "Ups-Center-Auto"
MARK = "ups-center-auto"
FORBIDDEN = ("merge", "ready", "close")          # gh pr subcommands this module must never issue


def branch_for(aid):
    return "wire/auto/" + aid


def marker(aid, digest):
    return "<!-- %s id=%s claims=%s -->" % (MARK, aid, digest)


def read_marker(text):
    m = re.search(r"<!-- %s id=(\S+) claims=(\S+) -->" % MARK, text or "")
    return (m.group(1), m.group(2)) if m else (None, None)


def _gh(run, args, cwd=None):
    if args and args[0] == "pr" and len(args) > 1 and args[1] in FORBIDDEN:
        raise RuntimeError("ups_center_pr refuses `gh pr %s`: publication stays with Keith" % args[1])
    return run(["gh"] + args, cwd)


def open_prs_for(run, article_path, cwd=None):
    rc, out = _gh(run, ["pr", "list", "--state", "open", "--limit", "100",
                        "--json", "number,headRefName,isDraft,url,body,files"], cwd)
    if rc != 0:
        raise RuntimeError("gh pr list failed: %s" % out[:300])
    prs = json.loads(out or "[]")
    return [p for p in prs if any(f.get("path") == article_path for f in p.get("files") or [])]


def editor_owned(run, pr, aid, cwd=None):
    """True unless the PR is on the automation's branch AND every commit since main
    carries the automation trailer."""
    if pr["headRefName"] != branch_for(aid):
        return True
    rc, out = run(["git", "log", "--format=%H|%(trailers:key=" + TRAILER + ",valueonly,separator=%x2C)",
                   "origin/main..origin/" + branch_for(aid)], cwd)
    if rc != 0:
        return True                                   # cannot prove ownership -> do not overwrite
    commits = [line for line in out.splitlines() if "|" in line]
    return not commits or any(not line.split("|", 1)[1].strip() for line in commits)


def changed_claims(old, new):
    """[{claim, was, now}] for claims whose value moved, appeared or disappeared."""
    out = []
    for k in sorted(set(old) | set(new)):
        a, b = (old.get(k) or {}).get("value"), (new.get(k) or {}).get("value")
        if a != b:
            out.append({"claim": k, "was": a, "now": b})
    return out


def body(aid, res, report, changes, preview_note):
    gaps = "\n".join("- **%s** (%s): %s" % (g["id"], g["section"], re.sub(r"<[^>]+>", "", g["why"])[:300])
                     for g in res["gaps"]) or "- none"
    errs = "\n".join("- " + x for x in report["errors"]) or "- none"
    ch = "\n".join("- `%s`: %s -> %s" % (c["claim"], json.dumps(c["was"]), json.dumps(c["now"])) for c in changes[:60]) \
        or "- none since the last draft"
    checked = ", ".join("%s %d" % kv for kv in sorted(report["checkedClaims"].items()))
    return ("## UPS Center %s: automated DRAFT\n\n"
            "**Do not merge.** Publication and the league announcement stay with Keith's review of this specific issue.\n\n"
            "**Status:** %s\n\n### Editor review needed\n%s\n\n### Validation against sources\n- claims checked: %s\n"
            "- errors:\n%s\n\n### Changed claims\n%s\n\n### Preview\n%s\n\n%s\n\n"
            "🤖 Generated by ups_center_auto.py\n" % (
                aid, "ready for review" if report["ok"] else "BLOCKED -- validation failed", gaps, checked, errs, ch,
                preview_note, marker(aid, res["claimsDigest"])))


def sync(run, aid, article_path, res, report, write_branch, preview_note="", cwd=None, dry=False, title_prefix=""):
    """Bring GitHub to one draft PR for `aid`. `write_branch()` rebuilds the auto branch's
    files in the work tree (only called for CREATE/UPDATE). Returns {action, pr, changes}."""
    prs = open_prs_for(run, article_path, cwd)
    if len(prs) > 1:
        return {"action": "stop-duplicate", "pr": [p["number"] for p in prs], "changes": []}
    if not prs:
        if dry:
            return {"action": "would-create", "pr": None, "changes": []}
        write_branch()
        rc, out = _gh(run, ["pr", "create", "--draft", "--base", "main", "--head", branch_for(aid),
                            "--title", "%sUPS Center %s: automated draft (do not merge)" % (title_prefix, aid),
                            "--body", body(aid, res, report, [], preview_note)], cwd)
        if rc != 0:
            raise RuntimeError("gh pr create failed: %s" % out[:300])
        return {"action": "created", "pr": out.strip().split("/")[-1], "changes": []}
    pr = prs[0]
    if editor_owned(run, pr, aid, cwd):
        return {"action": "editor-owned", "pr": pr["number"], "changes": []}
    _, old_digest = read_marker(pr.get("body"))
    if old_digest == res["claimsDigest"]:
        return {"action": "noop", "pr": pr["number"], "changes": []}
    rc, old_claims = run(["git", "show", "origin/%s:docs/wire/auto/%s/claims.json" % (branch_for(aid), aid)], cwd)
    changes = changed_claims(json.loads(old_claims) if rc == 0 else {}, res["claims"])
    if dry:
        return {"action": "would-update", "pr": pr["number"], "changes": changes}
    write_branch()
    _gh(run, ["pr", "edit", str(pr["number"]), "--body", body(aid, res, report, changes, preview_note)], cwd)
    _gh(run, ["pr", "comment", str(pr["number"]), "--body",
              "Draft rebuilt from new source data. %d changed claim(s):\n%s" % (
                  len(changes), "\n".join("- `%s`: %s -> %s" % (c["claim"], json.dumps(c["was"]), json.dumps(c["now"]))
                                          for c in changes[:60]))], cwd)
    return {"action": "updated", "pr": pr["number"], "changes": changes}


def comment_editor_pr(run, pr_number, aid, recheck, cwd=None, dry=False):
    """Post the re-check on an editor-owned draft once per distinct result."""
    digest = hashlib.sha256(json.dumps(recheck, sort_keys=True).encode()).hexdigest()[:12]
    rc, out = _gh(run, ["pr", "view", str(pr_number), "--json", "comments"], cwd)
    seen = rc == 0 and ("%s-recheck=%s" % (MARK, digest)) in out
    if seen:
        return {"action": "noop", "digest": digest}
    text = ("UPS Center automation re-checked this editor-owned draft against current sources (not overwritten).\n\n"
            "- changed claims since its scores were frozen: %s\n- quote problems: %s\n\n<!-- %s-recheck=%s -->" % (
                ", ".join("`%s` %s -> %s" % (c["claim"], c["was"], c["now"]) for c in recheck["changedClaims"]) or "none",
                "; ".join(recheck["errors"]) or "none", MARK, digest))
    if dry:
        return {"action": "would-comment", "digest": digest, "text": text}
    _gh(run, ["pr", "comment", str(pr_number), "--body", text], cwd)
    return {"action": "commented", "digest": digest}
