-- Tier A: 22 rows. Guarded, idempotent; see build_sql.py. Run 01_verify_before.sql first, 04_verify_after.sql after.

-- row 1233: /commish-contract-update player 16614 at 2026-06-01T15:51:19.739Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1233 tier=A evidence: code: every worker version live at 2026-06-01T15:51:19Z (32e25198) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #10 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1255 2026-06-04T16:27:05 /commish-contract-update st=200 before==this.before:True || activity log: Extension → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1233 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1233 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1233 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1233 %');

-- row 1234: /offer-restructure player 14779 at 2026-06-01T15:56:19.549Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1234 tier=A evidence: code: every worker version live at 2026-06-01T15:56:19Z (32e25198) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_restructure_submissions #1 dry_run=1 (written by the same handler from the request''s own flag) || activity log: Restructure → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1234 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1234 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1234 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1234 %');

-- row 1235: /offer-restructure player 14779 at 2026-06-01T15:56:51.276Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1235 tier=A evidence: code: every worker version live at 2026-06-01T15:56:51Z (32e25198) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_restructure_submissions #2 dry_run=1 (written by the same handler from the request''s own flag) || activity log: Restructure → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1235 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1235 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1235 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1235 %');

-- row 1236: /commish-contract-update player 16614 at 2026-06-01T18:18:23.120Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1236 tier=A evidence: code: every worker version live at 2026-06-01T18:18:23Z (677cb75a, 32e25198) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #11 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1255 2026-06-04T16:27:05 /commish-contract-update st=200 before==this.before:True || activity log: Extension → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1236 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1236 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1236 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1236 %');

-- row 1237: /commish-contract-update player 16614 at 2026-06-01T18:36:42.067Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1237 tier=A evidence: code: every worker version live at 2026-06-01T18:36:42Z (677cb75a) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #12 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1255 2026-06-04T16:27:05 /commish-contract-update st=200 before==this.before:True || activity log: Extension → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1237 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1237 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1237 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1237 %');

-- row 1240: /commish-contract-update player 16174 at 2026-06-03T13:47:54.433Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1240 tier=A evidence: code: every worker version live at 2026-06-03T13:47:54Z (36efe080, 73cdb515) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #13 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1241 2026-06-03T13:49:07 /commish-contract-update st=200 before==this.before:True || activity log: Multi-Year Contract → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1240 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1240 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1240 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1240 %');

-- row 1243: /commish-contract-update player 16174 at 2026-06-03T15:12:08.862Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1243 tier=A evidence: code: every worker version live at 2026-06-03T15:12:08Z (d1f6c41b) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #16 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1244 2026-06-03T15:12:18 /commish-contract-update st=200 before==this.before:True || activity log: Multi-Year Contract → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1243 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1243 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1243 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1243 %');

-- row 1246: /commish-contract-update player 16174 at 2026-06-03T20:54:56.824Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1246 tier=A evidence: code: every worker version live at 2026-06-03T20:54:56Z (59aede77, 432d96b4) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #19 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1247 2026-06-03T20:55:01 /commish-contract-update st=200 before==this.before:True'
  FROM salary_change_log WHERE id = 1246 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1246 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1246 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1246 %');

-- row 1248: /commish-contract-update player 16194 at 2026-06-04T13:11:41.764Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1248 tier=A evidence: code: every worker version live at 2026-06-04T13:11:41Z (9f00b7e9) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #21 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1268 2026-06-05T18:40:21 /offer-restructure st=200 before==this.before:True || activity log: Extension → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1248 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1248 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1248 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1248 %');

-- row 1250: /commish-contract-update player 13674 at 2026-06-04T16:25:24.435Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1250 tier=A evidence: code: every worker version live at 2026-06-04T16:25:24Z (43aecfef) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #23 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1251 2026-06-04T16:25:29 /commish-contract-update st=200 before==this.before:True'
  FROM salary_change_log WHERE id = 1250 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1250 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1250 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1250 %');

-- row 1253: /commish-contract-update player 14137 at 2026-06-04T16:26:15.325Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1253 tier=A evidence: code: every worker version live at 2026-06-04T16:26:15Z (43aecfef) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #26 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1254 2026-06-04T16:26:19 /commish-contract-update st=200 before==this.before:True || activity log: Extension → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1253 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1253 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1253 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1253 %');

-- row 1256: /commish-contract-update player 16614 at 2026-06-04T16:27:20.766Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1256 tier=A evidence: code: every worker version live at 2026-06-04T16:27:20Z (43aecfef) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #29 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1257 2026-06-04T16:27:24 /commish-contract-update st=200 before==this.before:True'
  FROM salary_change_log WHERE id = 1256 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1256 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1256 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1256 %');

-- row 1259: /commish-contract-update player 16252 at 2026-06-04T17:32:58.621Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1259 tier=A evidence: code: every worker version live at 2026-06-04T17:32:58Z (43aecfef) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #32 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1260 2026-06-04T17:33:03 /commish-contract-update st=200 before==this.before:True || activity log: Multi-Year Contract → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1259 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1259 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1259 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1259 %');

-- row 1262: /commish-contract-update player 16193 at 2026-06-04T22:29:11.592Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1262 tier=A evidence: code: every worker version live at 2026-06-04T22:29:11Z (43aecfef) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #35 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1263 2026-06-04T22:29:14 /commish-contract-update st=200 before==this.before:True || activity log: Multi-Year Contract → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1262 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1262 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1262 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1262 %');

-- row 1269: /commish-contract-update player 16194 at 2026-06-05T21:39:13.170Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1269 tier=A evidence: code: every worker version live at 2026-06-05T21:39:13Z (ac5bf9ad, ad60f753) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: same-request record ups_extension_submissions #658 dry_run=1 (written by the same handler from the request''s own flag) || MFL: next MFL-confirmed read of this player: 1620 2026-07-19T13:54:49 /admin/import-salaries st=200 before==this.before:False || activity log: Extension → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1269 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1269 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1269 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1269 %');

-- row 1271: /commish-contract-update player 16167 at 2026-06-05T21:40:45.826Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1271 tier=A evidence: code: every worker version live at 2026-06-05T21:40:45Z (ac5bf9ad, ad60f753) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: followed seconds later by the identical REAL request (1272 2026-06-05T21:40:50 /commish-contract-update st=200), whose before-state equals this row''s || activity log: Extension → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1271 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1271 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1271 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1271 %');

-- row 1698: /commish-contract-update player 16185 at 2026-07-28T02:50:50.295Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1698 tier=A evidence: code: every worker version live at 2026-07-28T02:50:50Z (6df05c67) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: followed seconds later by the identical REAL request (1701 2026-07-28T02:51:07 /commish-contract-update st=200), whose before-state equals this row''s || activity log: FA Contract → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1698 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1698 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1698 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1698 %');

-- row 1699: /commish-contract-update player 14833 at 2026-07-28T02:50:51.570Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1699 tier=A evidence: code: every worker version live at 2026-07-28T02:50:51Z (6df05c67) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: followed seconds later by the identical REAL request (1702 2026-07-28T02:51:10 /commish-contract-update st=200), whose before-state equals this row''s'
  FROM salary_change_log WHERE id = 1699 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1699 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1699 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1699 %');

-- row 1700: /commish-contract-update player 13696 at 2026-07-28T02:50:52.899Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1700 tier=A evidence: code: every worker version live at 2026-07-28T02:50:52Z (6df05c67) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: followed seconds later by the identical REAL request (1703 2026-07-28T02:51:13 /commish-contract-update st=200), whose before-state equals this row''s'
  FROM salary_change_log WHERE id = 1700 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1700 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1700 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1700 %');

-- row 1704: /commish-contract-update player 15290 at 2026-07-28T10:25:34.764Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1704 tier=A evidence: code: every worker version live at 2026-07-28T10:25:34Z (6df05c67) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: followed seconds later by the identical REAL request (1706 2026-07-28T10:25:47 /commish-contract-update st=200), whose before-state equals this row''s || activity log: FA Contract → silenced (test_flag 0)'
  FROM salary_change_log WHERE id = 1704 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1704 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1704 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1704 %');

-- row 1705: /commish-contract-update player 14778 at 2026-07-28T10:25:35.892Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1705 tier=A evidence: code: every worker version live at 2026-07-28T10:25:35Z (6df05c67) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: followed seconds later by the identical REAL request (1707 2026-07-28T10:25:49 /commish-contract-update st=200), whose before-state equals this row''s'
  FROM salary_change_log WHERE id = 1705 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1705 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1705 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1705 %');

-- row 1876: /commish-contract-update player 99999999 at 2026-10-07T20:13:55.092Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1876 tier=A evidence: code: every worker version live at 2026-10-07T20:13:55Z (750b32df, 4c1286cc) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || request: the 2026-10-07 auth-check probe; its body carried dry_run=1 (session record); its [DRY RUN] card is in the test Discord channel; its activity-log row was reverted in #1188'
  FROM salary_change_log WHERE id = 1876 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1876 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1876 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1876 %');
