-- Tier B: 5 rows. Guarded, idempotent; see build_sql.py. Run 01_verify_before.sql first, 04_verify_after.sql after.

-- row 1238: /commish-contract-update player 16212 at 2026-06-03T10:08:26.970Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1238 tier=B evidence: code: every worker version live at 2026-06-03T10:08:26Z (3ea58590, 4abe8774) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || MFL: next MFL-confirmed read of this player: 1834 2026-09-05T14:48:40 /commish-contract-update st=200 before==this.before:True || activity log: FA Contract → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1238 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1238 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1238 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1238 %');

-- row 1264: /offer-mym player 14836 at 2026-06-05T17:41:08.108Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1264 tier=B evidence: code: every worker version live at 2026-06-05T17:41:08Z (3eef1b46) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || MFL: next MFL-confirmed read of this player: 1806 2026-08-06T03:22:51 /admin/import-salaries st=200 before==this.before:True || activity log: FA Contract → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1264 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1264 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1264 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1264 %');

-- row 1265: /offer-mym player 14836 at 2026-06-05T18:21:57.271Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1265 tier=B evidence: code: every worker version live at 2026-06-05T18:21:57Z (a355cb92, 3eef1b46) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || MFL: next MFL-confirmed read of this player: 1806 2026-08-06T03:22:51 /admin/import-salaries st=200 before==this.before:True || activity log: MYM → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1265 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1265 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1265 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1265 %');

-- row 1266: /offer-mym player 14836 at 2026-06-05T18:22:17.626Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1266 tier=B evidence: code: every worker version live at 2026-06-05T18:22:17Z (a355cb92, 3eef1b46) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || MFL: next MFL-confirmed read of this player: 1806 2026-08-06T03:22:51 /admin/import-salaries st=200 before==this.before:True || activity log: MYM → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1266 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1266 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1266 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1266 %');

-- row 1267: /offer-mym player 14836 at 2026-06-05T18:24:01.002Z
INSERT INTO ups_contract_gate_audit (at_utc, season, field, before_val, after_val, actor, note)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), season, 'salary_change_log_dry_run_relabel',
         json_object('id', id, 'created_ts', created_ts, 'endpoint', endpoint, 'league_id', league_id, 'season', season, 'dry_run', dry_run, 'actor_ip', actor_ip, 'actor_ua', actor_ua, 'actor_had_api_key', actor_had_api_key, 'player_id', player_id, 'before_salary', before_salary, 'before_contract_status', before_contract_status, 'before_contract_year', before_contract_year, 'before_contract_info', before_contract_info, 'after_salary', after_salary, 'after_contract_status', after_contract_status, 'after_contract_year', after_contract_year, 'after_contract_info', after_contract_info, 'intended_salary', intended_salary, 'intended_contract_status', intended_contract_status, 'intended_contract_year', intended_contract_year, 'intended_contract_info', intended_contract_info, 'landed', landed, 'import_status', import_status, 'notes', notes),
         json_object('dry_run', 1, 'landed', 0, 'notes', notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'),
         'commissioner-approved relabel (plan 2026-10-08)', 'change_log_id=1267 tier=B evidence: code: every worker version live at 2026-06-05T18:24:01Z (ad60f753, a355cb92) writes landed=1 with import_status 0 only on the dry-run branch (13 checks, all hold) || row: import_status 0 (no MFL response) and before = after on all four contract fields (a real landed write requires an observed year/info/status change) || MFL: next MFL-confirmed read of this player: 1806 2026-08-06T03:22:51 /admin/import-salaries st=200 before==this.before:True || activity log: MYM → test (test_flag 0)'
  FROM salary_change_log WHERE id = 1267 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND NOT EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1267 %');
UPDATE salary_change_log SET dry_run = 1, landed = 0, notes = notes || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel'
  WHERE id = 1267 AND dry_run = 0 AND landed = 1 AND COALESCE(import_status, 0) = 0 AND notes = 'import_ok_log_dispatched' AND COALESCE(before_salary,'') = COALESCE(after_salary,'') AND COALESCE(before_contract_status,'') = COALESCE(after_contract_status,'') AND COALESCE(before_contract_year,'') = COALESCE(after_contract_year,'') AND COALESCE(before_contract_info,'') = COALESCE(after_contract_info,'')
    AND EXISTS (SELECT 1 FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel' AND note LIKE 'change_log_id=1267 %');
