-- READ-ONLY.
-- (1) every corrected row: dry_run=1, landed=0, original note kept as the prefix (expect one row per corrected id)
SELECT id, dry_run, landed, import_status, substr(notes, 1, 24) AS note_prefix FROM salary_change_log WHERE id IN (1233, 1234, 1235, 1236, 1237, 1238, 1240, 1243, 1246, 1248, 1250, 1253, 1256, 1259, 1262, 1264, 1265, 1266, 1267, 1269, 1271, 1698, 1699, 1700, 1704, 1705, 1876) ORDER BY id;
-- (2) exactly one audit record per corrected row (expect n = rows corrected, dupes = 0)
SELECT COUNT(*) AS n, COUNT(*) - COUNT(DISTINCT note) AS dupes FROM ups_contract_gate_audit WHERE field = 'salary_change_log_dry_run_relabel';
-- (3) NO other column changed: every unchanged column equals the original in its audit record (expect 0 rows)
SELECT s.id FROM salary_change_log s JOIN ups_contract_gate_audit a ON a.field = 'salary_change_log_dry_run_relabel' AND a.note LIKE 'change_log_id=' || s.id || ' %'
  WHERE NOT (json_extract(a.before_val, '$.id') IS s.id AND json_extract(a.before_val, '$.created_ts') IS s.created_ts AND json_extract(a.before_val, '$.endpoint') IS s.endpoint AND json_extract(a.before_val, '$.league_id') IS s.league_id AND json_extract(a.before_val, '$.season') IS s.season AND json_extract(a.before_val, '$.actor_ip') IS s.actor_ip AND json_extract(a.before_val, '$.actor_ua') IS s.actor_ua AND json_extract(a.before_val, '$.actor_had_api_key') IS s.actor_had_api_key AND json_extract(a.before_val, '$.player_id') IS s.player_id AND json_extract(a.before_val, '$.before_salary') IS s.before_salary AND json_extract(a.before_val, '$.before_contract_status') IS s.before_contract_status AND json_extract(a.before_val, '$.before_contract_year') IS s.before_contract_year AND json_extract(a.before_val, '$.before_contract_info') IS s.before_contract_info AND json_extract(a.before_val, '$.after_salary') IS s.after_salary AND json_extract(a.before_val, '$.after_contract_status') IS s.after_contract_status AND json_extract(a.before_val, '$.after_contract_year') IS s.after_contract_year AND json_extract(a.before_val, '$.after_contract_info') IS s.after_contract_info AND json_extract(a.before_val, '$.intended_salary') IS s.intended_salary AND json_extract(a.before_val, '$.intended_contract_status') IS s.intended_contract_status AND json_extract(a.before_val, '$.intended_contract_year') IS s.intended_contract_year AND json_extract(a.before_val, '$.intended_contract_info') IS s.intended_contract_info AND json_extract(a.before_val, '$.import_status') IS s.import_status) OR json_extract(a.before_val, '$.dry_run') <> 0 OR json_extract(a.before_val, '$.landed') <> 1
     OR s.notes <> json_extract(a.before_val, '$.notes') || ' | relabeled 2026-10-08: DRY RUN, no MFL request (import_status 0); originally logged dry_run=0 landed=1 by the contract-route audit-writer bug; original row + evidence in ups_contract_gate_audit field salary_change_log_dry_run_relabel';
-- (4) nothing left with the false label (expect n = 0 once both tiers are applied; = the Tier B count if only Tier A is)
SELECT COUNT(*) AS n FROM salary_change_log WHERE landed = 1 AND COALESCE(import_status, 0) = 0;
-- (5) the FCFS evidence rule is unaffected: the MFL-confirmed rows behind add event 52 are untouched (expect 1865, 1875 with dry_run 0, landed 1, 200)
SELECT id, dry_run, landed, import_status FROM salary_change_log WHERE id IN (1865, 1875) ORDER BY id;
