#!/usr/bin/env node
// Builds worker/src/admin_routes.js — the EXACT inventory of every /admin/* route the worker dispatches, scanned from the source that
// defines them (worker/src/index.js, worker/src/hall.js). The worker uses it to decide "is this a real admin route?" by exact match, so an
// unknown, wrong-method, wrong-case, doubled-slash, trailing-slash or URL-encoded admin path is a uniform 404 instead of falling through to
// a generic handler (production, 2026-09-25: any unmatched /admin/* answered 200 with the commissioner-state JSON).
//
//   node scripts/build_admin_route_table.mjs           # regenerate
//   node scripts/build_admin_route_table.mjs --check   # exit 1 if worker/src/admin_routes.js is stale (used by tests/admin_route_security.test.mjs)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCES = ["worker/src/index.js", "worker/src/hall.js"];
const OUT = path.join(ROOT, "worker/src/admin_routes.js");

// Routes that live under /admin but are deliberately PUBLIC read-only lists (owners read them in the Front Office, the mobile app and
// Team Operations). They keep answering without credentials; everything else under /admin is administrative.
export const PUBLIC_ADMIN_NAMESPACE_READS = ["GET /admin/contract-submissions"];

// Dynamic admin routes (an id segment) — the only non-literal ones in the source (`path.startsWith("/admin/rule-proposals/") && path.endsWith(...)`).
export const DYNAMIC = [
  { pattern: "^/admin/rule-proposals/[^/]+/(verdict|ruling|delete)$", methods: ["POST"] },
];

export function scan() {
  const routes = {};
  for (const rel of SOURCES) {
    const lines = fs.readFileSync(path.join(ROOT, rel), "utf8").split("\n");
    lines.forEach((line, i) => {
      // only lines that ROUTE (`path === "…"`), not the L-guard's `path !== "…"` exemptions or prose
      const paths = [...line.matchAll(/path === "(\/admin\/[^"?#]+)"/g)].map((m) => m[1]);
      if (!paths.length) return;
      // the method test is on the same line, or (multi-line conditions) within the next two lines
      const window = [line, lines[i + 1] || "", lines[i + 2] || ""].join(" ");
      const stop = window.indexOf("{");            // the condition ends at the block's opening brace
      const cond = stop > 0 ? window.slice(0, stop + 1) : window;
      const methods = [...cond.matchAll(/request\.method === "([A-Z]+)"/g)].map((m) => m[1]);
      for (const p of paths) {
        const set = new Set(routes[p] || []);
        for (const m of methods.length ? methods : ["*"]) set.add(m);
        routes[p] = [...set].sort();
      }
    });
  }
  return Object.fromEntries(Object.entries(routes).sort(([a], [b]) => a.localeCompare(b)));
}

export function render() {
  const routes = scan();
  const body = Object.entries(routes).map(([p, m]) => `  ${JSON.stringify(p)}: ${JSON.stringify(m)},`).join("\n");
  return `// GENERATED by scripts/build_admin_route_table.mjs — do not edit. \`node scripts/build_admin_route_table.mjs --check\` fails when this drifts
// from the routes actually defined in worker/src/index.js and worker/src/hall.js (tests/admin_route_security.test.mjs runs it).
//
// The EXACT set of /admin/* routes the worker dispatches: path -> allowed methods ("*" = the route itself doesn't restrict the method).
export const ADMIN_ROUTES = {
${body}
};

// Dynamic admin routes (an id segment).
export const ADMIN_DYNAMIC_ROUTES = ${JSON.stringify(DYNAMIC.map((d) => ({ ...d })), null, 2)}.map((r) => ({ re: new RegExp(r.pattern), methods: r.methods }));

// Public read-only lists that live under /admin (owner-facing clients read them without credentials).
export const PUBLIC_ADMIN_NAMESPACE_READS = new Set(${JSON.stringify(PUBLIC_ADMIN_NAMESPACE_READS)});
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const next = render();
  if (process.argv.includes("--check")) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (cur !== next) { console.error("worker/src/admin_routes.js is stale — run: node scripts/build_admin_route_table.mjs"); process.exit(1); }
    console.log(`admin route table up to date (${Object.keys(scan()).length} routes)`);
  } else {
    fs.writeFileSync(OUT, next);
    console.log(`wrote ${path.relative(ROOT, OUT)} (${Object.keys(scan()).length} routes)`);
  }
}
